### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by starship9** [96AA48/galaxygen#3]
`npm i galaxygen -g`

This doesn't seem to work on windows, I keep getting the "System cannot find the path specified" message,

`npm list`

also doesn't list galaxygen, somehow.

**Comment by 96AA48** [comment]
I'll do some testing later today to see if it works on Windows for me. Sorry for the inconvenience and thanks for reporting this issue!

**Comment by 96AA48** [comment]
Hey @starship9, I've looked into the issue with a new Windows virtual machine with fresh Node and NPM, and I haven't come across any issues. It seems that the error you are experiencing has something to do with NPM or the way that you have setup your environment.

Best of luck with coming to a solution!
